### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-1-infografia-Kim-Mendoza3#1]
https://drive.google.com/file/d/1MVNc2q6G8wWdvDNL_IqvL4PBQi4vyL8d/view?usp=sharing

**Comment by Luisangelriverosbautista** [comment]
FALTAN LAS REFERENCIAS.TODO ESTA BIEN A MI PARECER PERO POR LAS REFERENCIAS CONSIDERO QUE UN 18 ESTA BIEN COMO CALIFICACION

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
